In [2]:
pip install google-analytics-data

Requirement already satisfied: google-analytics-data in c:\programdata\anaconda3\lib\site-packages (0.17.1)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0 in c:\programdata\anaconda3\lib\site-packages (from google-analytics-data) (2.11.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in c:\programdata\anaconda3\lib\site-packages (from google-analytics-data) (4.24.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in c:\programdata\anaconda3\lib\site-packages (from google-analytics-data) (1.22.3)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\programdata\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (1.60.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\programdata\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (2.28.1)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in c:\programdata\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (2.22.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\programdata\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (1.57.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\programdata\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (1.57.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (5.3.1)
Requirement already satisfied: urllib3<2.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (1.26.14)
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (1.16.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\programdata\anaconda3\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (0.2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (3.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\programdata\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-analytics-data) (0.4.8)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd
import os

In [4]:
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import DateRange
from google.analytics.data_v1beta.types import Dimension
from google.analytics.data_v1beta.types import Metric
from google.analytics.data_v1beta.types import RunReportRequest
from google.analytics.data_v1beta.types import OrderBy

In [5]:
## Set up global variables -  Acura of Springfeild

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '262741996'

client = BetaAnalyticsDataClient()

In [6]:
## Format Report - run_report method
def format_report(request):
    response = client.run_report(request)
    
    # Row index
    row_index_names = [header.name for header in response.dimension_headers]
    row_header = []
    for i in range(len(row_index_names)):
        row_header.append([row.dimension_values[i].value for row in response.rows])

    row_index_named = pd.MultiIndex.from_arrays(np.array(row_header), names = np.array(row_index_names))
    # Row flat data
    metric_names = [header.name for header in response.metric_headers]
    data_values = []
    for i in range(len(metric_names)):
        data_values.append([row.metric_values[i].value for row in response.rows])

    output = pd.DataFrame(data = np.transpose(np.array(data_values, dtype = 'f')), 
                          index = row_index_named, columns = metric_names)
    return output

In [7]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/262741996"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [204]:
tempdf=format_report(request)

In [205]:
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Cross-network                  371.0       288.0            304.0
     Direct                         644.0       545.0            396.0
     Organic Search                 708.0       475.0            593.0
     Organic Social                 313.0       294.0             73.0
     Paid Search                    329.0       208.0            271.0
     Paid Social                    372.0       301.0            193.0
     Referral                        89.0        65.0             69.0
     Unassigned                    1786.0      1887.0              0.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Cross-network                  254.0        287.0
     Direct                         506.0        538.0
     Organic Search                 376.0        466.0
     Organic Social                 274.0        281.0
     Paid Search                    166.0        205.0
     Paid Social                    241.0        277.0
     Referral                        51.0         61.0
     Unassigned                       0.0        774.0

In [206]:
tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions']

1665.0

In [207]:
tempdf['sessions'].sum()

4612.0

In [208]:
column_names = ['MediaWeek','Client','Sessions', 'OrganicDirectSessions', 'OrganicSessions','DirectSessions','PaidSearchSessions','PaidSocialSessions','EmailSessions','Users','NewUsers']

# Create an empty DataFrame with the specified column names
empty_df = pd.DataFrame(columns=column_names)
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Acura of SpringField',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\3792959929.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [209]:
empty_df.head()

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0

In [ ]:
## Set up global variables -  Autogiants.com

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '395502240'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
column_names = ['MediaWeek','Client','Sessions', 'OrganicDirectSessions', 'OrganicSessions','DirectSessions','PaidSearchSessions','PaidSocialSessions','EmailSessions','Users','NewUsers']

# Create an empty DataFrame with the specified column names
empty_df = pd.DataFrame(columns=column_names)
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'AutoGiants.com',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables -  AutoGiantsMitsubishi.com  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '336703926'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
column_names = ['MediaWeek','Client','Sessions', 'OrganicDirectSessions', 'OrganicSessions','DirectSessions','PaidSearchSessions','PaidSocialSessions','EmailSessions','Users','NewUsers']

# Create an empty DataFrame with the specified column names
empty_df = pd.DataFrame(columns=column_names)
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'AutoGiantsMitsubishi.com',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables -  Carwise Peoria 
 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '335754701'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
column_names = ['MediaWeek','Client','Sessions', 'OrganicDirectSessions', 'OrganicSessions','DirectSessions','PaidSearchSessions','PaidSocialSessions','EmailSessions','Users','NewUsers']

# Create an empty DataFrame with the specified column names
empty_df = pd.DataFrame(columns=column_names)
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Carwise Peoria',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables -  Cortese Mitsubishi  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '334904629'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
column_names = ['MediaWeek','Client','Sessions', 'OrganicDirectSessions', 'OrganicSessions','DirectSessions','PaidSearchSessions','PaidSocialSessions','EmailSessions','Users','NewUsers']

# Create an empty DataFrame with the specified column names
empty_df = pd.DataFrame(columns=column_names)
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Cortese Mitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [154]:
## Set up global variables - EddKirby

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '331557856'

client = BetaAnalyticsDataClient()

In [155]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/395502240"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [156]:
tempdf=format_report(request)
tempdf

PermissionDenied: 403 User does not have sufficient permissions for this property. To learn more about Property ID, see https://developers.google.com/analytics/devguides/reporting/data/v1/property-id.

In [152]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Edd Kirby\'s Adventure',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\3792959929.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Evans Kia  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '398966054'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Evans Kia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Fairway Mitsubishi   

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '335831436'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Fairway Mitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Family Mitsubishi  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '373033737'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Family Mitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Fogg’s Automotive   

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '388292072'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Fogg’s Automotive ',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Frank Leta Automotive Outlet    

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '262674903'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Frank Leta Automotive Outlet',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Frank Leta Buick GMC     

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '346705715
'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Frank Leta Buick GMC ',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Glenbrook Hyundai     

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '369595966
'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Glenbrook Hyundai',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Langdale Kia      

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '398627877'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Langdale Kia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Leskovar Mitsubishi     

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '387062133'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Leskovar Mitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Mathews Acura      

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '331508061'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Mathews Acura',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Mathews Honda       

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '331578757'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Mathews Honda',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [ ]:
## Set up global variables - Mazda of Kent       

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '396639354'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Mazda of Kent',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df.head()

In [210]:
## Set up global variables - Strong VW main site

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '338434221'

client = BetaAnalyticsDataClient()

In [211]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/338434221"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [212]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                        1431.0       857.0           1190.0
     Organic Search                2789.0      1789.0           2492.0
     Organic Social                3290.0      2499.0           3282.0
     Paid Search                   1815.0      1537.0           1761.0
     Referral                     23182.0     22133.0            407.0
     Unassigned                      36.0        79.0              1.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         697.0        812.0
     Organic Search                1363.0       1763.0
     Organic Social                1875.0       2197.0
     Paid Search                   1398.0       1525.0
     Referral                     22329.0      22126.0
     Unassigned                      43.0         62.0

In [213]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'strong VW',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\2776635366.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [214]:
empty_df.head()

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0

In [215]:
## Set up global variables - Springfield Mitsubishi of READING 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '338344750'

client = BetaAnalyticsDataClient()

In [216]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/338344750"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [217]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         356.0       311.0            313.0
     Display                          1.0         1.0              0.0
     Organic Search                 419.0       263.0            338.0
     Organic Social                  21.0        15.0             21.0
     Paid Search                      6.0         6.0              0.0
     Referral                       285.0       227.0            272.0
     Unassigned                       4.0         4.0              0.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         299.0        309.0
     Display                          0.0          0.0
     Organic Search                 229.0        258.0
     Organic Social                  13.0         14.0
     Paid Search                      6.0          6.0
     Referral                       190.0        214.0
     Unassigned                       1.0          4.0

In [218]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'SpringfieldMitsubishiofREADING',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\2306341888.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [219]:
empty_df.head()

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0

In [220]:
## Set up global variables - PhillyDriveSpringfieldMitsubishi

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '338396237'

client = BetaAnalyticsDataClient()

In [221]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/338396237"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [222]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Cross-network                  182.0       115.0            162.0
     Direct                         666.0       500.0            546.0
     Display                        108.0        83.0             65.0
     Organic Search                 802.0       528.0            681.0
     Paid Search                    325.0       265.0            270.0
     Referral                        88.0        65.0             65.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Cross-network                   99.0        115.0
     Direct                         458.0        495.0
     Display                         83.0         81.0
     Organic Search                 423.0        515.0
     Paid Search                    242.0        259.0
     Referral                        57.0         64.0

In [223]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'PhillyDriveSpringfieldMitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\266041744.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [224]:
empty_df.head()

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0

In [225]:
## Set up global variables - Springfield Mitsubishi of Atlantic City 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '313252818'

client = BetaAnalyticsDataClient()

In [226]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/313252818"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [227]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         151.0       130.0             76.0
     Email                           71.0        71.0             45.0
     Organic Search                 188.0       123.0            147.0
     Organic Social                  58.0        52.0             41.0
     Referral                        14.0        11.0             11.0
     Unassigned                      14.0        12.0              8.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         123.0        130.0
     Email                           71.0         71.0
     Organic Search                 103.0        121.0
     Organic Social                  51.0         52.0
     Referral                        10.0         11.0
     Unassigned                       7.0         12.0

In [228]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'SpringfieldMitsubishiofAtlanticCity ',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    #'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1433657148.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [229]:
empty_df.head()

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0

In [230]:
## Set up global variables - South Suburban Mitsubishi  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '338432908'

client = BetaAnalyticsDataClient()

In [231]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/338432908"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [232]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         463.0       354.0            326.0
     Email                            3.0         3.0              2.0
     Organic Search                 896.0       686.0            698.0
     Paid Other                       3.0         1.0              1.0
     Referral                        64.0        47.0             36.0
     Unassigned                       5.0         5.0              1.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         335.0        349.0
     Email                            2.0          3.0
     Organic Search                 611.0        677.0
     Paid Other                       1.0          1.0
     Referral                        41.0         47.0
     Unassigned                       0.0          5.0

In [233]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'SouthSuburbanMitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Other']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1493300507.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [235]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0

In [236]:
## Set up global variables - serra Nissan grand blanc 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '382409693'

client = BetaAnalyticsDataClient()

In [237]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/382409693"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [238]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         244.0       170.0            186.0
     Organic Search                 331.0       213.0            285.0
     Organic Social                 695.0       522.0            375.0
     Paid Search                    511.0       438.0            377.0
     Referral                       494.0       367.0            306.0
     Unassigned                       7.0         7.0              1.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         150.0        168.0
     Organic Search                 162.0        210.0
     Organic Social                 392.0        459.0
     Paid Search                    391.0        438.0
     Referral                       258.0        311.0
     Unassigned                       2.0          5.0

In [239]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'SerraNissanGrandBlanc',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1858952557.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [240]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0

In [241]:
## Set up global variables - Sarasota Mitsubishi 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '273099199'

client = BetaAnalyticsDataClient()

In [242]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/273099199"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [243]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         166.0       147.0            121.0
     Email                           12.0        10.0              9.0
     Organic Search                 228.0       160.0            191.0
     Paid Search                     40.0        32.0             23.0
     Referral                        15.0        10.0             11.0
     Unassigned                       3.0         3.0              0.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         143.0        147.0
     Email                            5.0          9.0
     Organic Search                 123.0        158.0
     Paid Search                     27.0         31.0
     Referral                         9.0         10.0
     Unassigned                       0.0          3.0

In [245]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'SarasotaMitsubishi',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1129330668.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [246]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0

In [ ]:
## Set up global variables - Serra Automotive Group Website  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '320413124'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Automotive Group Website',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Chevrolet   

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '316842356'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Chevrolet',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Honda of Sylacauga    

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '317707378'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Honda of Sylacauga',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Gardendale Kia     

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '320911614'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Gardendale Kia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Trussville Kia      

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '320941226'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Trussville Kia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Sylacauga Nissan       

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321056234'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Sylacauga Nissan',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Tony Serra Nissan Cullman 17212       

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321057446'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Tony Serra Nissan Cullman 17212',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Nissan 17215       

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321039885'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Nissan 17215',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Volkswagen        

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321079466'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Volkswagen',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Tony Serra Highland Nissan        

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321067981'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Tony Serra Highland Nissan',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Serra Nissan Grand Blanc        

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '382409693'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Serra Nissan Grand Blanc',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Tony Serra Ford     

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '319031227'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Tony Serra Ford',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [247]:
## Set up global variables - Route 6 Auto Mall Kia 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '333115461'

client = BetaAnalyticsDataClient()

In [248]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/333115461"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [249]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Cross-network                  116.0       103.0             80.0
     Direct                         884.0       562.0            579.0
     Display                         79.0        78.0             24.0
     Email                           10.0         5.0             10.0
     Organic Search                1561.0      1192.0           1191.0
     Organic Social                  17.0        13.0             12.0
     Paid Search                    398.0       324.0            318.0
     Paid Video                     475.0       380.0            249.0
     Referral                       272.0       202.0            172.0
     Unassigned                     529.0       306.0            475.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Cross-network                   64.0         94.0
     Direct                         467.0        535.0
     Display                         67.0         77.0
     Email                            4.0          5.0
     Organic Search                1042.0       1178.0
     Organic Social                  12.0         13.0
     Paid Search                    262.0        321.0
     Paid Video                     322.0        366.0
     Referral                       147.0        189.0
     Unassigned                     190.0        292.0

In [250]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Route6AutoMallKia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions']+tempdf.loc['39'].loc['Paid Video']['sessions']+tempdf.loc['39'].loc['Display']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\4071255219.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [251]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0

In [255]:
## Set up global variables - RK Subaru 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321501798'

client = BetaAnalyticsDataClient()

In [256]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/321501798"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [257]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         296.0       236.0            199.0
     Email                            2.0         2.0              2.0
     Organic Search                 385.0       270.0            310.0
     Organic Social                   6.0         6.0              5.0
     Referral                        49.0        40.0             37.0
     Unassigned                       2.0         2.0              1.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         225.0        236.0
     Email                            2.0          2.0
     Organic Search                 223.0        270.0
     Organic Social                   6.0          6.0
     Referral                        33.0         40.0
     Unassigned                       0.0          2.0

In [258]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'RKSubaru',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    #'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions']+tempdf.loc['39'].loc['Paid Video']['sessions']+tempdf.loc['39'].loc['Display']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\2988948200.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [259]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0

In [260]:
## Set up global variables - RK Kia 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321544775'

client = BetaAnalyticsDataClient()

In [261]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/321501798"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [262]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         296.0       236.0            199.0
     Email                            2.0         2.0              2.0
     Organic Search                 385.0       270.0            310.0
     Organic Social                   6.0         6.0              5.0
     Referral                        49.0        40.0             37.0
     Unassigned                       2.0         2.0              1.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         225.0        236.0
     Email                            2.0          2.0
     Organic Search                 223.0        270.0
     Organic Social                   6.0          6.0
     Referral                        33.0         40.0
     Unassigned                       0.0          2.0

In [263]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'RKKia',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    #'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions']+tempdf.loc['39'].loc['Paid Video']['sessions']+tempdf.loc['39'].loc['Display']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\2988948200.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [264]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0

In [265]:
## Set up global variables - RK Chevrolet  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '321558089'

client = BetaAnalyticsDataClient()

In [266]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/321558089"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [267]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Cross-network                  404.0       307.0            310.0
     Direct                         415.0       326.0            254.0
     Email                            6.0         3.0              3.0
     Organic Search                 641.0       441.0            509.0
     Organic Social                   6.0         6.0              5.0
     Paid Other                       1.0         1.0              0.0
     Paid Search                    221.0       187.0            171.0
     Referral                        78.0        54.0             52.0
     Unassigned                       8.0         9.0              3.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Cross-network                  262.0        307.0
     Direct                         280.0        322.0
     Email                            3.0          3.0
     Organic Search                 373.0        437.0
     Organic Social                   6.0          6.0
     Paid Other                       1.0          1.0
     Paid Search                    149.0        183.0
     Referral                        41.0         53.0
     Unassigned                       2.0          7.0

In [268]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'RKChevrolet',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions']+tempdf.loc['39'].loc['Paid Other']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\70169481.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [269]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
11,9/24 - 9/30,RKChevrolet,1780.0,1062.0,647.0,423.0,222.0,NaN,6.0,1319.0,1117.0

In [271]:
empty_df.loc[10]['Client'] = 'RKKia'

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\2306188879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty_df.loc[10]['Client'] = 'RKKia'

In [272]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
11,9/24 - 9/30,RKChevrolet,1780.0,1062.0,647.0,423.0,222.0,NaN,6.0,1319.0,1117.0

In [273]:
## Set up global variables - Michiana CDJR  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '338356159'

client = BetaAnalyticsDataClient()

In [274]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/338356159"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [275]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                        1434.0      1141.0           1211.0
     Email                           34.0        26.0             33.0
     Organic Search                 892.0       609.0            805.0
     Organic Shopping                 6.0         6.0              6.0
     Organic Social                 424.0       327.0            414.0
     Paid Search                    956.0       774.0            911.0
     Paid Social                    242.0       230.0            196.0
     Referral                       994.0       843.0            896.0
     Unassigned                       8.0         8.0              0.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                        1084.0       1128.0
     Email                           16.0         26.0
     Organic Search                 480.0        601.0
     Organic Shopping                 6.0          6.0
     Organic Social                 231.0        289.0
     Paid Search                    700.0        768.0
     Paid Social                    212.0        221.0
     Referral                       666.0        787.0
     Unassigned                       0.0          8.0

In [277]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'MichianaCDJR',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Organic Shopping']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1080354657.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [278]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
11,9/24 - 9/30,RKChevrolet,1780.0,1062.0,647.0,423.0,222.0,NaN,6.0,1319.0,1117.0
12,9/24 - 9/30,MichianaCDJR,4990.0,2750.0,1322.0,1442.0,956.0,242.0,34.0,3834.0,3395.0

In [ ]:
## Set up global variables - Merchants Auto   

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '356439272'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Merchants Auto',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Organic Shopping']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Portage Chevrolet   

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '348085000'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Portage Chevrolet',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Organic Shopping']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - Rack Electric    

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '323048190'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'Rack Electric',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Organic Shopping']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [ ]:
## Set up global variables - RC Hill Mitsubishi Ocala    

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '251348209'

client = BetaAnalyticsDataClient()

In [ ]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

In [ ]:
tempdf=format_report(request)

In [ ]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'RC Hill Mitsubishi Ocala',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Organic Shopping']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

In [ ]:
empty_df

In [279]:
## Set up global variables - McLeod Auto Sales 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '357437270'

client = BetaAnalyticsDataClient()

In [280]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/357437270"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [281]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         398.0       299.0            342.0
     Organic Search                 562.0       459.0            490.0
     Organic Social                   4.0         4.0              3.0
     Paid Search                    162.0       118.0            145.0
     Referral                         9.0         6.0              8.0
     Unassigned                       3.0         3.0              0.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         263.0        298.0
     Organic Search                 406.0        459.0
     Organic Social                   2.0          4.0
     Paid Search                     87.0        118.0
     Referral                         5.0          6.0
     Unassigned                       0.0          3.0

In [282]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'McLeodAutoSales',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Search']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\1069357485.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [283]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
11,9/24 - 9/30,RKChevrolet,1780.0,1062.0,647.0,423.0,222.0,NaN,6.0,1319.0,1117.0
12,9/24 - 9/30,MichianaCDJR,4990.0,2750.0,1322.0,1442.0,956.0,242.0,34.0,3834.0,3395.0
13,9/24 - 9/30,McLeodAutoSales,1138.0,964.0,566.0,401.0,162.0,NaN,NaN,888.0,763.0

In [284]:
## Set up global variables - Mathews Dodge Marion  

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'ga4_service.json'
property_id = '357168965'

client = BetaAnalyticsDataClient()

In [285]:
request = RunReportRequest(
        property='properties/'+property_id,
        dimensions=[Dimension(name="week"), 
                    #Dimension(name="sessionMedium"),
                   Dimension(name="sessionDefaultChannelGroup")],
        metrics=[Metric(name="sessions"), 
                 Metric(name="totalUsers"),
                 Metric(name="engagedSessions"),
                Metric(name="newUsers"),
                Metric(name="activeUsers")],
        order_bys = [OrderBy(dimension = {'dimension_name': 'week'}),
                    OrderBy(dimension = {'dimension_name': 'sessionDefaultChannelGroup'})],
    date_ranges=[DateRange(start_date="2023-09-24", end_date="2023-09-30")],
        #date_ranges=[DateRange(start_date="2023-09-24", end_date="today")],
    )

request

property: "properties/357168965"
dimensions {
  name: "week"
}
dimensions {
  name: "sessionDefaultChannelGroup"
}
metrics {
  name: "sessions"
}
metrics {
  name: "totalUsers"
}
metrics {
  name: "engagedSessions"
}
metrics {
  name: "newUsers"
}
metrics {
  name: "activeUsers"
}
date_ranges {
  start_date: "2023-09-24"
  end_date: "2023-09-30"
}
order_bys {
  dimension {
    dimension_name: "week"
  }
}
order_bys {
  dimension {
    dimension_name: "sessionDefaultChannelGroup"
  }
}

In [286]:
tempdf=format_report(request)
tempdf

                                 sessions  totalUsers  engagedSessions  \
week sessionDefaultChannelGroup
39   Direct                         586.0       466.0            460.0
     Organic Search                 753.0       438.0            608.0
     Organic Social                  12.0        10.0             10.0
     Paid Other                     165.0       116.0            108.0
     Referral                        73.0        63.0             39.0
     Unassigned                      40.0        40.0             16.0

                                 newUsers  activeUsers
week sessionDefaultChannelGroup
39   Direct                         428.0        455.0
     Organic Search                 330.0        425.0
     Organic Social                   6.0         10.0
     Paid Other                     103.0        110.0
     Referral                        53.0         63.0
     Unassigned                      18.0         40.0

In [287]:
values_to_add = {
    'MediaWeek':'9/24 - 9/30',
    'Client':'MathewsDodgeMarion',
    'Sessions': tempdf['sessions'].sum(),
    'OrganicDirectSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions']+tempdf.loc['39'].loc['Direct']['sessions'],
    'OrganicSessions': tempdf.loc['39'].loc['Organic Social']['sessions']+tempdf.loc['39'].loc['Organic Search']['sessions'],
    'DirectSessions': tempdf.loc['39'].loc['Direct']['sessions']+tempdf.loc['39'].loc['Unassigned']['sessions'],
    'PaidSearchSessions':tempdf.loc['39'].loc['Paid Other']['sessions'],
    #'PaidSocialSessions':tempdf.loc['39'].loc['Paid Social']['sessions'],
    #'EmailSessions':tempdf.loc['39'].loc['Email']['sessions'],
    'Users':tempdf['activeUsers'].sum(),
    'NewUsers':tempdf['newUsers'].sum()
}
empty_df = empty_df.append(values_to_add, ignore_index=True)

C:\Users\Vrashi\AppData\Local\Temp\ipykernel_13592\850998337.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  empty_df = empty_df.append(values_to_add, ignore_index=True)

In [288]:
empty_df

,MediaWeek,Client,Sessions,OrganicDirectSessions,OrganicSessions,DirectSessions,PaidSearchSessions,PaidSocialSessions,EmailSessions,Users,NewUsers
0,9/24 - 9/30,Acura of SpringField,4612.0,1665.0,1021.0,644.0,329.0,372.0,NaN,2889.0,1868.0
1,9/24 - 9/30,strong VW,32543.0,7510.0,6079.0,1431.0,1815.0,NaN,NaN,28485.0,27705.0
2,9/24 - 9/30,SpringfieldMitsubishiofREADING,1092.0,796.0,440.0,356.0,6.0,NaN,NaN,805.0,738.0
3,9/24 - 9/30,PhillyDriveSpringfieldMitsubishi,2171.0,1468.0,802.0,666.0,325.0,NaN,NaN,1529.0,1362.0
4,9/24 - 9/30,SpringfieldMitsubishiofAtlanticCity,496.0,397.0,246.0,151.0,NaN,NaN,NaN,397.0,365.0
5,9/24 - 9/30,SouthSuburbanMitsubishi,1434.0,1359.0,896.0,463.0,3.0,NaN,NaN,1082.0,990.0
6,9/24 - 9/30,SerraNissanGrandBlanc,2282.0,1270.0,1026.0,251.0,511.0,NaN,NaN,1591.0,1355.0
7,9/24 - 9/30,SarasotaMitsubishi,464.0,394.0,228.0,169.0,40.0,NaN,NaN,358.0,307.0
8,9/24 - 9/30,Route6AutoMallKia,4341.0,2462.0,1578.0,1413.0,952.0,NaN,10.0,3070.0,2577.0
9,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
10,9/24 - 9/30,RKSubaru,740.0,687.0,391.0,298.0,NaN,NaN,2.0,556.0,489.0
11,9/24 - 9/30,RKChevrolet,1780.0,1062.0,647.0,423.0,222.0,NaN,6.0,1319.0,1117.0
12,9/24 - 9/30,MichianaCDJR,4990.0,2750.0,1322.0,1442.0,956.0,242.0,34.0,3834.0,3395.0
13,9/24 - 9/30,McLeodAutoSales,1138.0,964.0,566.0,401.0,162.0,NaN,NaN,888.0,763.0
14,9/24 - 9/30,MathewsDodgeMarion,1629.0,1351.0,765.0,626.0,165.0,NaN,NaN,1103.0,938.0

In [39]:
output_df = format_report(request)

In [289]:
empty_df.to_csv('GA4_python_output_latest_week.csv')

In [ ]:
#putting data into exel file

In [7]:
import pandas as pd
import openpyxl as xl 
from openpyxl import load_workbook

# Load the Excel file into a DataFrame
excel_file_path = 'Weekly Analytics Week of 10.01.2023.xlsx'

df = pd.read_excel(excel_file_path, sheet_name='Sheet1')

In [9]:
df

,Clients Up:,,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Clients Down:,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BASED ON ORGANIC & DIRECT Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Percentage Calculation: (Newest Week - Previou...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jerry DeFalco Advertising,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,9/10 - 9/16,Dude Thrill Seekers,12743,7500,6221,1279,1673,3570,0,6679,...,54,27,0.014675,0.55615,0.519231,,NaN,NaN,NaN,NaN
762,9/3 -9/9,Dude Thrill Seekers,8854,6797,5754,1043,1455,321,0,5681,...,30,29,0.018974,0.333333,0.535714,,NaN,NaN,NaN,NaN
763,8/27 - 9/2,Dude Thrill Seekers,6942,4398,3235,1163,689,1019,0,4834,...,39,25,0.023912,0.385542,0.609375,NaN,NaN,NaN,NaN,NaN
764,8/20 - 8/26,Dude Thrill Seekers,6809,3462,2320,1142,802,1000,0,4622,...,29,35,0.028639,0.25641,0.58,NaN,NaN,NaN,NaN,NaN
765,8/13 - 8/19,Easy As 1234 Strong/(8/15) Dude Thrill Seekers,7378,3256,2300,956,1520,965,0,5259,...,38,41,0.024261,0.346369,0.612903,NaN,NaN,NaN,NaN,NaN